services:
  - type: web
    name: ea-search
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: GOOGLE_SEARCH_API_KEY
        sync: false
      - key: GOOGLE_SEARCH_ENGINE_ID
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
    healthCheckPath: /api/test 